### ISSUE TITLE
Implement Repository Pattern

### ISSUE THREAD

**Issue by YanaSlavcheva** [LakeMead/OnlineStore#4]
Implement Repository Pattern with Generic Repository, Deletable Entity Repository and other custom Repositories for Entity Models.

**Comment by KristianMariyanov** [comment]
See those examples for idea:
- https://github.com/EverlastingStudent/EverlastingStudent/blob/master/Source/EverlastingStudent/EverlastingStudent.Data/Repositories/Contracts/IDeletableEntityRepository.cs
- https://github.com/EverlastingStudent/EverlastingStudent/blob/master/Source/EverlastingStudent/EverlastingStudent.Data/Repositories/DeletableEntityRepository.cs

**Comment by KristianMariyanov** [comment]
- [x]

**Comment by KristianMariyanov** [comment]
Custom repositories are not implement yet

**Comment by YanaSlavcheva** [comment]
Closed with commit e978fa23714ccc41aabb08eb26d676c8a064bb9e
